#!/bin/bash

# This is a thin wrapper around utopiacoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using utopiacoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_UTOPIACOIND

# Grab the value of $REAL_UTOPIACOINCLI which may be utopiacoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_UTOPIACOINCLI}" "$@" | sed 's/\r//'
